### ISSUE TITLE
How to do your ablation study

### ISSUE THREAD

**Issue by 22strongestme** [hq-deng/RD4AD#1]
Dear Author 
      I want to do the ablation study of your network ,but i have some question about it 。
![ablation_table](https://user-images.githubusercontent.com/55016895/161994558-a9798f67-89be-48ea-a971-3fafd0095a06.png)
if I want to use the single-layer features M1,  how should I do the ablation study,like the first pic below or the latter one?
![ablation1](https://user-images.githubusercontent.com/55016895/161995352-49042de2-78b9-4548-ab00-b513c8934792.png)
![ablation2](https://user-images.githubusercontent.com/55016895/161995366-7f94b90b-402d-4012-913d-af3fd79570e5.png)

**Comment by hq-deng** [comment]
Tis ablation study is from the first one. Please set "inputs[0], outputs[0]" in test.py line#83: "anomaly_map, _ = cal_anomaly_map(inputs, outputs, img.shape[-1], amap_mode='a')". Similar operation for other layers.

**Comment by hq-deng** [comment]
The second graph is not reasonable. But you can remove the multi-scale fusion. By replace "decoder(bn(inputs))" by "decoder(inputs)" for both main.py and test.py.

**Comment by 22strongestme** [comment]
thanks a lot ，I'll try it !!!
