### ISSUE TITLE
Question about the missing checkpoints.

### ISSUE THREAD

**Issue by EricLee0224** [hq-deng/RD4AD#10]

**Comment by EricLee0224** [comment]
Thanks for your great work and codes! 
How can I get the checkpoints:wres50_lego.pth ?
![图片](https://user-images.githubusercontent.com/96402054/179141516-6af5b653-a63a-40e2-842c-64d2582756f9.png)

**Comment by hq-deng** [comment]
Hello, wres50_lego.pth is defined and trained by yourself. Please check variable "ckp_path" in main.py .
