### ISSUE TITLE
Can this model perform classification?

### ISSUE THREAD

**Issue by AppleJoker94** [hq-deng/RD4AD#11]
Hi, first I was deeply impressed by your model, and I have a question

Is auroc_sp the number of classification?

Can this model perform classication?

Thank you for your wonderful work and I look forward to your reply.

**Comment by hq-deng** [comment]
Hello, I'm sorry for late reply. Auroc need a score in the range of [0,1] to reflect the classification performance, so it does not require a binary classification result such as accuracy. If you want to take a binary classification result, you should set a threshold for the anomaly score e.g. S>threshold is 1 and S<=threshold is 0.

**Comment by AppleJoker94** [comment]
I found anomaly score in def evaluation! Thank you!
