### ISSUE TITLE
Code for cifar10

### ISSUE THREAD

**Issue by zhangzjn** [hq-deng/RD4AD#15]
Hi, could you provide the code for cifar10 dataset to produce reported  86.5 AUROC? That would be very helpful, thanks

**Comment by hq-deng** [comment]
[https://drive.google.com/file/d/1OGNRzVy12vNNux_Ugeuo6qkFdo-NjV5V/view](url)

**Comment by hq-deng** [comment]
[Please find the code with thik link and run occ_train.py.](https://drive.google.com/file/d/1OGNRzVy12vNNux_Ugeuo6qkFdo-NjV5V)
