### ISSUE TITLE
where to find Supplementary Material

### ISSUE THREAD

**Issue by letmejoin** [hq-deng/RD4AD#3]
Thks for your work, but I can't find Supplementary Material in your paper. How can I find the Supplementary Material?
![image](https://user-images.githubusercontent.com/24537107/163345364-6cf66990-1cb0-4eb7-a6a0-1bc34c0ddc96.png)

**Comment by hq-deng** [comment]
https://drive.google.com/file/d/1aSu0FzL1LKkU_0Y1vKVAcnq-I4MKhkCU/view?usp=sharing

**Comment by letmejoin** [comment]
> https://drive.google.com/file/d/1aSu0FzL1LKkU_0Y1vKVAcnq-I4MKhkCU/view?usp=sharing

thanks for your sharing!!!
